In [1]:
import torch
from torch import nn
from torch.nn import functional as F
import numpy

In [2]:
class Identity(nn.Module):
    def __init__(self):
        super(Identity, self).__init__()

    def forward(self, x):
        return 1* x

In [3]:
model = Identity()

In [4]:
def backward_print(module, grad_in, grad_out):
    print('gradient with respect to the output of layer: ')
    print(grad_out[0].data)
backstat_hook = lambda module, grad_in, grad_out: backward_print(module, grad_in, grad_out)
backward_handle = model.register_backward_hook(backstat_hook)

In [5]:
#loss_fn = 'mse_loss' 
loss_fn = 'cross_entropy'
batch = 1
width = 2
x = torch.zeros(batch, width, requires_grad=True)
yhat=model(x)
if loss_fn == 'mse_loss':
    y = torch.tensor([[0, 1.]]*batch)
else:
    y = torch.tensor([1]*batch)

print('target: ')
print(y)
print('estimate: ')
print(yhat)

target: 
tensor([1])
estimate: 
tensor([[0., 0.]], grad_fn=<MulBackward0>)


In [6]:
loss = getattr(F, loss_fn)(yhat, y)
loss.backward( retain_graph=True)
print('gradient stored in variable: ')
print(x.grad)
backward_handle.remove()

gradient with respect to the output of layer: 
tensor([[ 0.5000, -0.5000]])
gradient stored in variable: 
tensor([[ 0.5000, -0.5000]])


In [7]:
y

tensor([1])